knp_paginator:
    page_range: 5
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
    template:
        pagination: 'layouts/partials/_pagination.html.twig'
        # sortable: 'layouts/partials/_sortable.html.twig'
