twig:
    default_path: '%kernel.project_dir%/templates'

    globals:
        #services: '@App\Service\AppServices'
        locales: "%locales%"
        #google_maps_api_key: "%google_maps_api_key%"
        date_format: "%date_format%"
        date_format_date_only: "%date_format_date_only%"
        date_timezone: "%date_timezone%"

    date:
        format: "%date_format%"
        timezone: "%date_timezone%"

when@test:
    twig:
        strict_variables: true
