twig:
    default_path: '%kernel.project_dir%/templates'
    # form_themes: ['form/bootstrap_5_layout.html.twig']

    form_themes:
        - 'form/layout.html.twig'
        - 'form/fields.html.twig'

    globals:
        # Service
        # services: '@App\Service\AppServices'

        # Language
        locales: "%app_locales%"

        # Google
        #google_maps_api_key: "%google_maps_api_key%"

        # Date and time
        date_format: "%date_format%"
        date_format_date_only: "%date_format_date_only%"
        date_timezone: "%date_timezone%"

        # Delete & Update Post\Ad
        delete_post_by_owner_only: '%post.delete.by_owner_only%'
        update_post_by_owner_only: '%post.update.by_owner_only%'

        delete_ad_by_owner_only: '%ad.delete.by_owner_only%'
        update_ad_by_owner_only: '%ad.update.by_owner_only%'

    date:
        format: "%date_format%"
        timezone: "%date_timezone%"

when@test:
    twig:
        strict_variables: true
