vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:

        category_image:
            uri_prefix: '%categories%'
            upload_destination: '%kernel.project_dir%/public%categories%'
            namer: vich_uploader.namer_uniqid
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        attachments:
            uri_prefix: '%attachments%'
            upload_destination: '%kernel.project_dir%/public%attachments%'
            namer: vich_uploader.namer_uniqid
            directory_namer:
                service: Vich\UploaderBundle\Naming\CurrentDateTimeDirectoryNamer
                options:
                    date_time_format: 'Y' # will create directory "2023/13/01" for curent date "2023-01-13"
                    date_time_property: createdAt # see above example
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        blog_post_image:
            uri_prefix: '%blog_post_image%'
            upload_destination: '%kernel.project_dir%/public%blog_post_image%'
            namer: vich_uploader.namer_uniqid
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        homepage_hero_custom_background:
            uri_prefix: '%homepage_hero_custom_background%'
            upload_destination: '%kernel.project_dir%/public%homepage_hero_custom_background%'
            namer: vich_uploader.namer_uniqid
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        app_layout:
            uri_prefix: '%app_layout%'
            upload_destination: '%kernel.project_dir%/public%app_layout%'
            namer: vich_uploader.namer_uniqid
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        icons:
            upload_destination: '%kernel.project_dir%/public%icons%'
            uri_prefix: '%icons%'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'slug' }

        user_avatar:
            uri_prefix: '%user_avatar%'
            upload_destination: '%kernel.project_dir%/public%user_avatar%'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options:
                    property: id
            directory_namer:
                service: App\Interface\Uploads\PropertyGroupedDirectoryNamer
                options:
                    property: id
                    modulo: 10000
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
