controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix: /{_locale}/
    requirements:
        _locale: '%locales%'
    defaults:
        _locale: '%locale%'
    #trailing_slash_on_root: false

api:
    resource: ../src/Controller/Api
    type: attribute
    prefix: /{_locale}/api/
    requirements:
        _locale: '%locales%'
    name_prefix: api_
